global:
  scrape_interval:     5s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [
        'localhost:9090',
        'dockerhost:5000',
        'dockerhost:5009']